owner: PARAMQ 
repo: status 

sites:
  - name: Go-Agent
    url: $GO_AGENT
  - name: Go-Agent API
    url: $API_GO_AGENT
  - name: PayQ Client
    url: $PAYQ_CLIENT
  - name: PayQ Admin
    url: $PAYQ_ADMIN
  - name: PayQ API
    url: $PAYQ_API
    
assigness:
  - paulspartan14
  - rnovec

status-website:
  cname: status.paramq.com
  logoUrl: https://paramq.com/assets/images/paramq_logo.png
  favicon: https://paramq.com/assets/images/paramq_logo.png
  name: ParamQ status
  introTitle: " "
  introMessage: " "
  theme: night
  navbar:
    - title: Status
      href: /
